let revenue = 1672300;
let monthlyDivisor
let Januaryy = 7;
document.getElementById(`January`).innerHTML = (revenue  * Januaryy)/100 + `$`;
console.log(January);
let February = 13;
document.getElementById(`February`).innerHTML = (revenue  * February)/100 + `$`;
console.log(February);
let March = 9;
document.getElementById(`March`).innerHTML = (revenue  * March)/100 + `$`;
console.log(March);
let April = 6;
document.getElementById(`April`).innerHTML = (revenue  * April)/100 + `$`;
console.log(April);
let May = 4;
document.getElementById(`May`).innerHTML = (revenue  * May)/100 + `$`;
console.log(May);
let June = 8;
document.getElementById(`June`).innerHTML = (revenue  * June)/100 + `$`;
console.log(June);
let July = 10;
document.getElementById(`July`).innerHTML = (revenue  * July)/100 + `$`;
console.log(July);
let August = 4;
document.getElementById(`August`).innerHTML = (revenue  * August)/100 + `$`;
console.log(August);
let September = 12;
document.getElementById(`September`).innerHTML = (revenue * September)/100 + `$`;
console.log(September);
let October = 8;
document.getElementById(`October`).innerHTML = (revenue  * October)/100 + `$`;
console.log(October);
let November = 7;
document.getElementById(`November`).innerHTML = (revenue  * November)/100 + `$`;
console.log(November);
let December = 12;
document.getElementById(`December`).innerHTML = (revenue  * December)/100 + `$`;
console.log(December);
